### ISSUE TITLE
Something strange with "p diff" calculation 

### ISSUE THREAD

**Issue by joe-ave** [Netgalleria/arska-node#19]
Hello Olli,

I just discovered that there is something strange with the "p diff" calculation, price were 6,1 c/Kw and 9h avg was 6,6 and 24h avg was 6,3.
The p diff for 24H should have been -0,2 and p diff 9H should have been -0,5, but instead they showed 0,0 and -0,3.

![image](https://user-images.githubusercontent.com/85622380/198319996-381d0ef0-8c38-42c6-97e2-5015f89e9451.png)

//Jonas

**Comment by Olli69** [comment]
Thanks Jonas again!
There was a rounding error with negative values. Now it should be fixed (in the code pushed to the repo), but I will still test it a bit before publishing a new binary release.

Olli

**Comment by Olli69** [comment]
P-diff rounding problem is fixed in latest 0.92.0-stable. There can be still 0.1 differences in rounded values in some cases, because calculations are made with precise values.
