### ISSUE TITLE
Variables looks shifted 1 hour forward but chart looks ok

### ISSUE THREAD

**Issue by joe-ave** [Netgalleria/arska-node#26]
Hello Olli,

by some reason the values in variables looks shifted forward 1 hour but the values in chart looks ok.
I have not seen this before so maybe it´s a behaviour that appears at dayshifting, hour 23 -> 00?

//Jonas

![day hour no offset chart](https://user-images.githubusercontent.com/85622380/218283422-8a0a9833-3d92-482a-8477-bec64562217f.png)
![day hour offset variable](https://user-images.githubusercontent.com/85622380/218283425-60d3948a-77cb-40dd-8fda-023dbf5cb92e.png)
![day hour offset variable 2](https://user-images.githubusercontent.com/85622380/218283428-0533ef20-8d52-45dd-ba75-5437ce45bdf2.png)

**Comment by Olli69** [comment]
Hi Jonas,
After a quick look, it looks like the graph and variables are ok (at least price, price ranks etc look good) but the updated time at the bottom is possibly wrong time zone (EET not CET you are using).  Needs further investigation...

EDIT: I just tested that if you have CET timezone on your computer but EET in Arska config - that could cause similar phenomen. Could you check Arska timezone settings on Admin part, thanks.

Olli

**Comment by joe-ave** [comment]
Hello Olli,

the price rank at hour 23 should have been something like 16, pricerank showing 23 indicates that the variables thinks that the hour is 00 of next day and not hour 23 at current day.

//Jonas

**Comment by Olli69** [comment]
Hi Jonas,
Did you check timezone settings?  In EET timezone, it would be already next day - that would explain it. Graph timezone comes from your local computer settings . 

Olli

**Comment by joe-ave** [comment]
Hello Olli,

since I live in SE3 it´s UTC+1, and the graph and price corresponds to actual prices in entso-e and Nordpool.
But if the pricerank evaluation uses EET it´s probably wrong for SE3 that would need UTC+1 instead otherwise it will be offset by one hour.

//Jonas

**Comment by Olli69** [comment]
Hi Jonas,
So you have these settings in the admin settings of Arska?

<img width="577" alt="image" src="https://user-images.githubusercontent.com/1752838/218315085-b969f9c7-f24a-4e91-af7a-a4a8a7d1565d.png">

Olli

**Comment by joe-ave** [comment]
Hello Olli,

I missed that one!, it was in EET.
Now variable 115 shows current hour and the pricerank calculation looks ok.

Thanks!

//Jonas
