### ISSUE TITLE
Strange upload behaviour

### ISSUE THREAD

**Issue by joe-ave** [Netgalleria/arska-node#8]
In order to get an Arska-Node installation to work on a Wemos d1 R32 I at first need to install Arska and from there put it to OTA uppdate mode and install littlefs and firmware for Arska-Node.
Once that is done I can change code and build/upload/monitor from Visual Studio, but if try to build filesystem and download that first in the Arska-Node project and then upload code my esp32 just restarts constantly every 2 
Upload via the webbpage gives same result.

So it’s just like the setup of the filesystem is different between Arska and Arska-Node and by some reason it causes my board to crash, or my building enviroment is missing something needed in Arska-Node but not in Arska.

**Comment by Olli69** [comment]
I checked the problem (also recorded by another user at the discussion forum). There was an error that occurred on a fresh install (or if you erased the flash memory on install). Updates of an existing installation have been working.

Now the bug with memory handling is fixed and [the install page](https://iot.netgalleria.fi/arska-install/) has updated files. Full install (with erase) is tested with esp32doit-devkit-v1 releases from the install page.

To prevent such problems in the future we will use more release/version control in the future. I added two sets of files to the installation page: stable and latest. In the first release, they are the same but in the future, stable files are better tested (older) versions than the latest version.

This repository [https://github.com/Netgalleria/arska-node](https://github.com/Netgalleria/arska-node) has the latest code and updates. In the future, you should not need other repositories.
